# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
transposed_array = np.transpose(array)
print("Original Array:\n", array)
print("Transposed Array:\n", transposed_array)

Original Array:
 [[14  9 80]
 [16 14 53]
 [68 50  7]]
Transposed Array:
 [[14 16 68]
 [ 9 14 50]
 [80 53  7]]


# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np
arr1 = np.arange(10)
arr2 = arr1.reshape(2, 5)
arr3= arr1.reshape(5, 2)
print("Original 1D Array:\n", arr1)
print("Reshaped 2x5 Array:\n", arr2)
print("Reshaped 5x2 Array:\n", arr3)

Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np
arr = np.random.rand(4, 4)
arr1 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:\n", arr)
print("6x6 Array with Border of Zeros:\n", arr1)

Original 4x4 Array:
 [[0.54606375 0.96066217 0.63777237 0.7529255 ]
 [0.68581254 0.04365695 0.00207054 0.82097302]
 [0.40250403 0.92457451 0.16480719 0.44368887]
 [0.79140083 0.06715112 0.28969322 0.2277873 ]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54606375 0.96066217 0.63777237 0.7529255  0.        ]
 [0.         0.68581254 0.04365695 0.00207054 0.82097302 0.        ]
 [0.         0.40250403 0.92457451 0.16480719 0.44368887 0.        ]
 [0.         0.79140083 0.06715112 0.28969322 0.2277873  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
import numpy as np
arr=np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [12]:
import numpy as np
lis=['python','numpy','pandas']
arr=np.array(lis)
print(arr)
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [14]:
import numpy as np
lis=['python','numpy','pandas']
arr=np.array(lis)
res=np.array([' '.join(word) for word in arr])
print(res)

['p y t h o n' 'n u m p y' 'p a n d a s']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [18]:
import numpy as np
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,5,(3,3))
print("arr1 is:\n",arr1)
print("arr2 is:\n",arr2)
print("arr1+arr2 is\n",arr1+arr2)
print("arr1-arr2 is\n",arr1-arr2)
print("arr1*arr2 is\n",arr1*arr2)
print("arr1/arr2 is\n",arr1/arr2)

arr1 is:
 [[3 1 1]
 [1 2 4]
 [4 1 1]]
arr2 is:
 [[2 1 1]
 [4 2 4]
 [1 1 3]]
arr1+arr2 is
 [[5 2 2]
 [5 4 8]
 [5 2 4]]
arr1-arr2 is
 [[ 1  0  0]
 [-3  0  0]
 [ 3  0 -2]]
arr1*arr2 is
 [[ 6  1  1]
 [ 4  4 16]
 [ 4  1  3]]
arr1/arr2 is
 [[1.5        1.         1.        ]
 [0.25       1.         1.        ]
 [4.         1.         0.33333333]]


# 8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [21]:
import numpy as np
arr=np.eye(5)
print("identity matrix is\n",arr)
res=np.diag(arr)
print("diagonal elements:\n",res)

identity matrix is
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
diagonal elements:
 [1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [22]:
import numpy as np
arr1=np.random.randint(0,1001,100)
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
        return True
def find_primes(arr):
    primes=[num for num in arr if is_prime(num)]
    return primes
find_primes(arr1)

[np.int32(273),
 np.int32(399),
 np.int32(925),
 np.int32(981),
 np.int32(105),
 np.int32(417),
 np.int32(979),
 np.int32(301),
 np.int32(645),
 np.int32(565),
 np.int32(483),
 np.int32(607),
 np.int32(281),
 np.int32(659),
 np.int32(525),
 np.int32(967),
 np.int32(181),
 np.int32(889),
 np.int32(187),
 np.int32(899),
 np.int32(999),
 np.int32(475),
 np.int32(407),
 np.int32(859),
 np.int32(375),
 np.int32(597),
 np.int32(917),
 np.int32(267),
 np.int32(399),
 np.int32(435),
 np.int32(603),
 np.int32(689),
 np.int32(37),
 np.int32(681),
 np.int32(317),
 np.int32(287),
 np.int32(789),
 np.int32(443),
 np.int32(155)]

# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [24]:
import numpy as np
np.random.seed(0)
daily_temp=np.random.randint(low=15,high=30,size=28)
weekly_temp=daily_temp.reshape(4,7)
weekly_avg=np.mean(weekly_temp,axis=1)
print("daily temperatures:\n",daily_temp)
print("weekly averages:\n",weekly_avg)

daily temperatures:
 [27 20 15 18 26 18 22 24 18 20 17 19 22 21 23 23 27 25 16 21 22 22 29 23
 16 20 24 28]
weekly averages:
 [20.85714286 20.14285714 22.42857143 23.14285714]
